[package]
name = "soundcloud-go-client"
version = "0.1.5"
edition = "2021"

[dependencies]
tao = "0.37"
wry = "0.57"
dirs = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"

[build-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(windows)'.dependencies]
webview2-com = "0.39.1"
windows = { version = "0.62", features = ["Win32_System_Com"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
