[package]
name = "golow"
version = "0.2.0"
edition = "2021"
description = "A fast, low-overhead unofficial desktop client for SoundCloud on Windows"
license = "MIT"
repository = "https://github.com/Alx8g/golow"
publish = false

[dependencies]
tao = "0.37"
wry = "0.57"
dirs = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
tray-icon = { version = "0.26", default-features = false }
qrcode = { version = "0.14", default-features = false }

[build-dependencies]
embed-resource = "3.0.11"
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(windows)'.dependencies]
webview2-com = "0.39.1"
windows = { version = "0.62", features = ["Data_Xml_Dom", "Foundation", "UI_Notifications", "Win32_Graphics_Gdi", "Win32_Networking_WinHttp", "Win32_Security_Cryptography", "Win32_System_Com", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Registry", "Win32_System_Threading", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true
